#!/bin/sh

set -e

ACTS="apagar dropbox uma casa proxy_on servidores reboot proxy_off"
ACTS="hibernate $ACTS"

action=`zenity --list --text 'THE GAME' --column accion $ACTS`
wifi_cmd='/home/carl/dev/ratpoison/wifi.py'
if [ "$action" = "uma" ]
then
  $wifi_cmd uni
elif [ "$action" = "casa" ]
then
  $wifi_cmd casa
elif [ "$action" = "proxy_on" ]
then
  $wifi_cmd proxy
elif [ "$action" = "proxy_off" ]
then
  $wifi_cmd noproxy
elif [ "$action" = "apagar" ]
then
  init 0
elif [ "$action" = "dropbox" ]
then
  su carl -c '~/.dropbox-dist/dropboxd'
elif [ "$action" = "reboot" ]
then
  init 6
elif [ "$action" = "hibernate" ]
then
  s2disk
elif [ "$action" = "servidores" ]
then
  /etc/init.d/apache2 start
  sudo mkdir /var/run/mysqld/
  sudo chmod 777 /var/run/mysqld/
  sudo mysqld
fi

