bangs = (
("Google Images","gi"),
("Mapquest","mapquest"),
("How Things Work","howthingswork"),
("Ling.pl","ling"),
("TV Tropes","tvtropes"),
("dict.cc","dictcc"),
("AlternativeTo","alto"),
("Albumart (Music)","albumartcd"),
("Baseball-Reference","br"),
("mooTools Docs","moo"),
("ebay (ES)","ebes"),
("Van Dale","vandale"),
("Netcraft","netcraft"),
("Mamont","mmnt"),
("The Free Dictionary","tfd"),
("Goear","goear"),
("Google Finance","stock"),
("CSMonitor","csmonitor"),
("C# MSDN","csharp"),
("Python3.0 Docs","python30"),
("Sulit","sulit"),
("Charity Navigator","charitynavigator"),
("Download.com","download"),
("MirBSD Manpages","mbsdman"),
("Dot TK","dottk"),
("QR Code Search","qr"),
("Mathematica Documentation Center","mathematica"),
("Wikipedia (JA)","wja"),
("GitHub.com","gh"),
("RT","rtnews"),
("Google Images","wallpaper"),
("Baixaki","baixaki"),
("Slackbuilds","slackbuilds"),
("SongMeanings","songmeanings"),
("OneDDL","1ddl"),
("ebay.be","ebbe"),
("Aljazeera English","aljazeera"),
("ebay.com.sg","ebaysg"),
("Engadget","engadget"),
("The Session","thesession"),
("webmenu","webmenu"),
("TV Guide","tvguide"),
("Ipernity","ipernity"),
("PHP.net","phpnet"),
("Search.USA.gov","usa"),
("Flickr","flickr"),
("Veekun Pokedex","veekun"),
("The Chakra Project Pakcages","chakrapkg"),
("TeX Stack Exchange","tex"),
("Unscatter.com","unscatter"),
("John Lewis","johnlewis"),
("Hi5","hi5"),
("Amazon.com","am"),
("IPS","ips"),
("WolframAlpha","wolfram"),
("Pkgsrc.se","pkgsrc"),
("Wykop","wykop"),
("123people","123people"),
("Dogpile","dogpile"),
("Scroogle","scroogle"),
("Java Docs","javadocs"),
("Google Ad Planner","adplanner"),
("Adobe Kuler","kuler"),
("DotNet Docs",".net"),
("GoogleBSD","bsd"),
("GamePro","gamepro"),
("Naver Korean-English Dictionary","naver"),
("Trailer Addict","trailer"),
("Wiktionary","wiktionary"),
("Rolling Stone","rollingstone"),
("AppBrain","appbrain"),
("Wikipedia (NL)","wnl"),
("Google de.Wikipedia","gwpde"),
("ebay.ca","ebayca"),
("Geizhals","giezhals"),
("Alla Bolag","allabolag"),
("Google ZA","gza"),
("Google RU","gru"),
("0l3.de","013"),
("Google GR","ggr"),
("YUI Docs","yui"),
("Ubuntu Packages","upackages"),
("artcyclopedia.com","artwork"),
("WolframAlpha","wolframalpha"),
("Whitewater Search Engine","whitewater"),
("Microsoft Knowledge Base","mskb"),
("appnr","appnr"),
("Half.com","half"),
("11870","11870"),
("RedZ","redz"),
("Binsearch","binsearch"),
("Kick Ass Torrents","kat"),
("Newgrounds","newgrounds"),
("Twitter","tw"),
("Theoretical Computer Science - Stack Exchange","cstheory"),
("IMDB","imdb"),
("CRAN","cran"),
("DomainTools.com","whois"),
("Baidu","baidu"),
("Bing Images","bi"),
("RubyDoc.info","rdoc"),
("DownForEveryone?","downfor"),
("MAC Address","mac"),
("FindLunchIn","findlunchin"),
("CreativeCommons.org","cc"),
("DHL","dhl"),
("Debian Mailing Lists","debml"),
("Jetwick","jetwick"),
("iWantMyName","iwant"),
("Uitzending Gemist","uzg"),
("Tyda.se","tyda"),
("Valleywag","valleywag"),
("Docjar","docjar"),
("Michaelis - Portugues - English","michaelis"),
("ActiveState.com","activestate"),
("Thesaurus.com","like"),
("Google MY","gmy"),
("Wordreference fr->en","wrfe"),
("Gamezebo","gamezebo"),
("Tureng Dictionary","tureng"),
("ebay.it","ebayit"),
("Safe search off","safeoff"),
("MSDN","msdn"),
("ebay.nl","ebnl"),
("TMZ","tmz"),
("NOAA","noaa"),
("Microsoft","microsoft"),
("ebay.ph","ebph"),
("Sporcle","sporcle"),
("MenuPages","mpla"),
("MenuPages","mpch"),
("The Wall Street Journal","wsj"),
("O'Reilly","orielly"),
("Art of Problem Solving Wiki","aops"),
("TVRage","tvrage"),
("ABCNews","abcnews"),
("Project Gutenberg","gutenberg"),
("DomainTools.com","ping"),
("Bing Videos","bvideos"),
("Anime News Network","animenewsnetwork"),
("Flickriver","flickriver"),
("Google Translate URL","gturl"),
("SimplyHired","simplyhired"),
("Fenopy","fenopy"),
("Google ID","gid"),
("NHL.com","nhl"),
("Edgar","edgart"),
("Wikitravel","wikitravel"),
("Google Blogs","blogs"),
("Bing Images","bimages"),
("StubHub","tickets"),
("True Knowledge","trueknowledge"),
("MagmaWiki","magma"),
("Google (Past Day)","gday"),
("DICT.org","dict"),
("Google Shopping","gshopping"),
("Science Blogs","scienceblogs"),
("Lavva","lavva"),
("Estante Virtual (by publisher)","evirted"),
("Wikipedia","w"),
("Netflix","netflix"),
("Oracle.com","oracle"),
("Bing","bing"),
("CPAN","oldcpan"),
("Gentoo Packages","ebuilds"),
("GriCal","grical"),
("NRC Next","nrcnext"),
("Google NO","gno"),
("Clojure Docs","clojuredocs"),
("Google HU","ghu"),
("port Lookup","port"),
("NzbMatrix","nzbmatrix"),
("Lucire","lucire"),
("Google Scholar","scholar"),
("CNBC","cnbc"),
("DeviantART","deviantart"),
("ebay.fr","ebfr"),
("Kick Ass Torrents","kickasstorrents"),
("Bing Maps","bingmaps"),
("Thesaurus.com","synonyms"),
("HP","hp"),
("RetailgMeNot","retailmenot"),
("TinyPic","tinypic"),
("Codeplex","codeplex"),
("Amazon.com","price"),
("Google TW","gtw"),
("Vimdoc","vimdoc"),
("WordReference","wr"),
("Wikipedia mobile","wm"),
("PackageMapping","package"),
("Greater Victoria Public Library","gvpl"),
("Fefes Blog","fefe"),
("MAC Address","macaddress"),
("Bing","b"),
("Trip Advisor","tripadvisor"),
("IconFinder","icons"),
("MenuPages","mpfl"),
("PySide","pyside"),
("Mercado Livre","mercadolivre"),
("TiVo","tivo"),
("Exalead","exalead"),
("Is Up?","isup"),
("Barnes & Noble","bn"),
("RubyGems","rubygems"),
("Snopes.com","snopes"),
("Google Movies","showtimes"),
("SpanishDict","sdict"),
("Infochimps","data"),
("Target","target"),
("Infochimps","infochimps"),
("JeuxVideo","jeux"),
("Google News Germany","gnde"),
("Google News","news"),
("Wikipedia (EO)","weo"),
("Nciku.com","nciku"),
("LEO Dictionary Spanish","leos"),
("CEAN","cean"),
("ebay.com.sg","ebsg"),
("Forkd","forkd"),
("Ikso Kantaro","ikso"),
("Vagalume","vagalume"),
("TigerDirect","tigerdirect"),
("Estante Virtual (by title)","evirttit"),
("GameFAQs.com","gamefaqs"),
("Yacy","yacy"),
("Clusty","clusty"),
("Google PL","gpl"),
("Google Local","glocal"),
("ebay.pl","ebaypl"),
("AP","ap"),
("Microsoft","ms"),
("CNRTL","cnrtl"),
("Ubuntuusers","ubuntuusers"),
("ColdFusion Docs","cf"),
("MenuPages","mp"),
("Road & Track","roadandtrack"),
("Scala","scala"),
("CakePHP book","cakebook"),
("BBC Food","bbcfood"),
("Cartoon Network","cartoonnetwork"),
("CPAN","searchcpan"),
("Myfonts","myfonts"),
("Prisjakt","prisjakt"),
("nLab","nlab"),
("Hotukdeals","hotukdeals"),
("YouTube","yt"),
("Ask Ubuntu","askubuntu"),
("Playlist.com","playlist"),
("ArsTechnica","ars"),
("Acronyms","acronym"),
("Google Code","code"),
("CarMagazine.co.uk","carmag"),
("Scribd.com","docs"),
("stackexchange.com","sx"),
("Know Your Meme","knowyourmeme"),
("Nvidia","nvidia"),
("VersionTracker.com","versiontracker"),
("FatWallet","fatwallet"),
("All Recipes","allrecipes"),
("Zemljevid Najdi.si","zemljevid"),
("Anime News Network","ann"),
("PHP.net","php"),
("ebay.de","ebayde"),
("Podcast.com","podcast"),
("Django Docs","djangome"),
("WWWJDIC","wwwjdic"),
("Google Images (Safe Off)","gisoff"),
("ebay.co.uk","ebayuk"),
("WeatherBug","weatherbug"),
("WOW Armory (EU)","wowarmoryeu"),
("RSeek","rseek"),
("Merriam-Webster","merriamwebster"),
("Ultimate Guitar","ug"),
("Interactive Fiction Database","ifdb"),
("Jamendo","jamendo"),
("oremus Bible Browser","obb"),
("OMG! Ubuntu!","omgu"),
("YouTube","video"),
("Google Maps","map"),
("Daring Fireball","df"),
("CheatCC.com","cheatcc"),
("Torrent Freak","torrentfreak"),
("Okay Geek","okgeek"),
("PerlMonks.org","perlmonks"),
("eBay","e"),
("Google (Past 24h)","g24"),
("Biography.com","biography"),
("Google Shopping","shopping"),
("Google US","gus"),
("GamesRadar","gamesradar"),
("Najdi.si","najdi"),
("allkpop","kpop"),
("HowtoForge","howtoforge"),
("man.cx","man"),
("ebay.com.hk","ebayhk"),
("Linux Cross Reference","lxr"),
("PALGN","palgn"),
("KDE Bugs","kbugs"),
("The Book Depository","bookdepository"),
("Google Maps","gmaps"),
("WordReference","wordreference"),
("Bookflavor","bookflavor"),
("Lifehacker","lh"),
("ebay.at","ebat"),
("NewsDay.com","newsday"),
("Scribd","scribd"),
("Yahoo! Shopping","shop"),
("http://live.gnome.org/Vala","vala"),
("The Star","thestar"),
("Punchfork","recipe"),
("MetaFilter","mefi"),
("SBA","sba"),
("the register","theregister"),
("Google DK","gdk"),
("DNS Lookup","dns"),
("DuckDuckGo","bangs"),
("etymonline.com","etym"),
("Wordnik","wordnik"),
("Monoprice","monoprice"),
("Python2.6 Docs","python26"),
("NovoSeek","novoseek"),
("LuaForge","luaforge"),
("LaunchPad","launchpad"),
("Bol.com","bol"),
("C2 Wiki","c2"),
("FreshPorts","freshports"),
("PhotoBucket.com","photobucket"),
("RhymeZone","rhyme"),
("ZDNet","zdnet"),
("MLB.com","mlb"),
("CakePHP API","cake"),
("searchco.de","searchcode"),
("Amazon.com","books"),
("Apple","apple"),
("Wikitravel","wikit"),
("Pylons Docs","pylons"),
("WordPress.org","wp"),
("delicious","delicious"),
("Flickr (comm/deriv)","flickrc"),
("iTunes","itunes"),
("ebay.pl","ebpl"),
("Lifehacker","lifehacker"),
("GigaOM","gigaom"),
("MathOverflow","mathoverflow"),
("Alternate","alternate"),
("AccuWeather","accuweather"),
("The Weather Network","wnetwork"),
("Google PT","gpt"),
("Linux Mint Forums","linuxmint"),
("Google Trends","gtrends"),
("Smogon University","smog"),
("Trisquel","trisquel"),
("Amazon.co.jp","amjp"),
("WolframAlpha","walpha"),
("SuperDownloads","superdownloads"),
("3tailer","3tailer"),
("Zoho","zoho"),
("The Onion","theonion"),
("RedFin","redfin"),
("Matlab File Exchange","mathworks"),
("TNT","tnt"),
("Xmarks | Boomark Sync and Search","xmarks"),
("MyAllSearch","myallsearch"),
("JavaScript Docs","javascript"),
("Discovery.com","discovery"),
("Gabriel Weinberg's Blog","yegg"),
("Yahoo! TV","tv"),
("Gmane","gmane"),
("OpenPorts","openports"),
("IGN","ign"),
("Bulbapedia","bulba"),
("SummitPost","summitpost"),
("Web of Trust","weboftrust"),
("v.gd","vgd"),
("USA Today","usatoday"),
("Python3 Docs","python3"),
("MenuPages","mpsf"),
("Yahoo! Images","yimages"),
("G4TV","g4tv"),
("Wikipedia (DE)","wde"),
("Yummly","yummly"),
("The Unofficial Apple Weblog (TUAW)","tuaw"),
("Debian Packages","dpts"),
("Pypi.python.org","pypi"),
("Smogon University","smogon"),
("GMail.com","gmail"),
("Videosift","videosift"),
("The Hype Machine","hypem"),
("Google Wikipedia","gwp"),
("WolframAlpha","wa"),
("Google AE","gae"),
("RocketHub","rockethub"),
("BibleGateway","bible"),
("ebay.com.my","ebaymy"),
("CrunchyRoll","crunchyroll"),
("Morningstar Search","morningstar"),
("Amazon Kindle","kindle"),
("Entireweb","entireweb"),
("HackageDB","hackage"),
("Joomla","jed"),
("Compfight","compfight"),
("Reverse DNS","rdns"),
("Opera Extensions","operaext"),
("Google Groups","gg"),
("KDE Community Wiki","kcommunity"),
("Amazon.com","buy"),
("IBM","ibm"),
("Thesaurus.com","thesaurus"),
("DuckDuckGo","ddg"),
("wallbase","wallbase"),
("Alexa","alexa"),
("ParlySearch","parlysearch"),
("Yahoo! News","ynews"),
("Wikipedia (EN)","wen"),
("Bing Videos","bvideo"),
("HNsearch","yc"),
("Monster.com","monster"),
("BeeMP3","bmp3"),
("Seznam","seznam"),
("OpenBook","openbook"),
("Google CH","gch"),
("Clker","clker"),
("Google Reader","gr"),
("ebay.ie","ebayie"),
("Erlang Docs","erlang"),
("DarkLyrics.com","darklyrics"),
("Google Patents","gpat"),
("Know Your Meme","kym"),
("Estante Virtual (all)","evirt"),
("Processing.org","proc"),
("Web2Py","web2py"),
("Netgear","netgear"),
("Food.com","food"),
("Google FI","gfi"),
("RFC-Editor.org","rfc"),
("W3C.org","w3c"),
("Mflow","mflow"),
("Forbes","forbes"),
("d20 SRD","d20srd"),
("Google Latest","glatest"),
("DigitalSpy","digitalspy"),
("Folha de S. Paulo","folha"),
("MSMVPs.com","msmvps"),
("TIGSource","tig"),
("Debian Packages","dpackages"),
("LaTex Code","latex"),
("Amazon.de","ade"),
("Google BR","gbr"),
("Mercury News","mercurynews"),
("Costco.com","costco"),
("TechDirt","techdirt"),
("artcyclopedia.com","artist"),
("WordPress.org Plugins","wpplugins"),
("Wiktionnaire","wiktfr"),
("Espacenet","espacenet"),
("gists.github.com","gist"),
("Google Cache","cached"),
("Wakoopa","wakoopa"),
("KDE TechBase","ktb"),
("DOI.org","doi"),
("ReadWriteWeb","readwriteweb"),
("Facebook","facebook"),
("Google Images","images"),
("FreeBSD Cross Reference","fxr"),
("Developpez.com","developpez"),
("OMG! Ubuntu!","omgubuntu"),
("Biznar","biznar"),
("PDFs","pdf"),
("SHODAN","shodan"),
("Macworld","macworld"),
("Octopart","octopart"),
("LibraryThing","librarything"),
("GoDaddy","godaddy"),
("dribbble","dribble"),
("True Knowledge","tknowledge"),
("Launchpad","lp"),
("LEO Dictionary Italian","leoi"),
("Qype","qype"),
("SitePoint Reference","spr"),
("Batlyrics","batlyrics"),
("Google TR","gtr"),
("Last.fm","lastfm"),
("Opera Extension","opera"),
("Wikipedia (ES)","wes"),
("Emuparadise","rom"),
("Google Images (Safe Off)","gisafeoff"),
("Brinked","ringtones"),
("Estante Virtual (by author)","evirtau"),
("Morningstar Quote","msq"),
("Memory Alpha","malpha"),
("stackexchange.com","stackexchange"),
("News Now","newsnow"),
("Youdao","youdao"),
("Web of Trust","mywot"),
("Slate.fr","slatefr"),
("Twitter","twitter"),
("Facebook","fb"),
("Weather Underground","wunderground"),
("aniDB","anidb"),
("Yandex","yandex"),
("MVNRepository","mvn"),
("MacPorts","macports"),
("InfoSpace","whitepages"),
("TotalCmd.Net","totalcmd"),
("Google Books","gb"),
("Spezify","spezify"),
("Scirus","scirus"),
("Ticket Master","ticketmaster"),
("Yahoo!","y"),
("Rotten Tomatoes","rottentomatoes"),
("Hark","hark"),
("AlternativeTo","altto"),
("Pinboard","pinboard"),
("Aion Wiki","aion"),
("Diigo","diigo"),
("PerezHilton","perezhilton"),
("My Opera","myopera"),
("Common Vulnerabilities and Exposures (CVE)","cve"),
("Moviepilot DE","moviepilot"),
("CultureUnplugged.com","cultureunplugged"),
("Magiccards.info","magiccards"),
("SpanishDict","spanishdict"),
("Google SL","gsl"),
("Google Scholar - Legal Opinion Section","legal"),
("Torrentz.com","torrentz"),
("SunTimes","suntimes"),
("Minecraft Wiki","minecraft"),
("All Experts","allexperts"),
("Earth911.com","recycle"),
("Tweetgrid","tweetgrid"),
("KDE Git Projects","kprojects"),
("Apple Discussions","applediscuss"),
("dict.cc","dcc"),
("Yippy","yippy"),
("PortableApps.com","portableapps"),
("http://dirae.es/","dirae"),
("Google Docs Viewer","gviewer"),
("The Online Encyclopedia Of Integer Sequences","seq"),
("Seamonkey Add-on","seamonkey"),
("Yahoo!","yahoo"),
("Microsoft Academic","academic"),
("Cplusplus.com","cplusplus"),
("Free Dictionary","fd"),
("Wiktionary","wt"),
("Google VN","gvn"),
("Download.com","software"),
("ebay.nl","ebaynl"),
("TinyURL.com","tinyurl"),
("The Chakra Project Forum","chakraforum"),
("Peppermint OS forums","peppermintos"),
("XDA-Developers Forum","xda"),
("Wikia","wikia"),
("Free Software Foundation","fsf"),
("SQL Alchemy Docs","sqlalchemy"),
("LEO Dictionary Russian","leor"),
("Google IE","gie"),
("The Chakra Project Community Repository","chakraccr"),
("GNU","gnu"),
("Leboncoin.fr","leboncoin"),
("UltimateGuitar.com","tabs"),
("Pplware","pplware"),
("Wowpedia","wowpedia"),
("Google Photos","gphotos"),
("JavaDocs.org","javadoc"),
("Open Clip Art Library","ocal"),
("Play-asia","playasia"),
("Google Scholar","gsc"),
("Wikipedia (NO)","wno"),
("Mangafox","mangafox"),
("Jeffrey's Exif Viewer","exif"),
("Fedora Project","fedorawiki"),
("123people","123p"),
("Google UK","guk"),
("Ubuntu Forums","ubuntuforums"),
("ebay.ca","ebca"),
("Answers.com","answers"),
("OpenStreetMap","osm"),
("Web of Trust","wot"),
("Programming Simplified","psimplified"),
("W3Schools.com","w3"),
("China Digital Times","cdt"),
("iStockPhoto","istockphoto"),
("Vocabolario Italiano-Esperanto (Minnaja)","iteo"),
("d20 SRD","d20"),
("eBay","eb"),
("Regular Expression Library","regex"),
("MagmaWiki","magmawiki"),
("StubHub","stubhub"),
("Dell","dell"),
("Digg","digg"),
("Wayback Machine","wayback"),
("ebay (ES)","ebayes"),
("Lenovo","lenovo"),
("Drupal API","dapi"),
("HNsearch","hnsearch"),
("Know Your Meme","meme"),
("RBL Lookup","rbl"),
("Find People on Plus","fonplus"),
("MIT PGP Public Key Server Lookup","pgp"),
("Jalopnik","jalop"),
("Spinoza","spinoza"),
("Techcrunch","tc"),
("Salon.com","salon"),
("The Online Slang Dictionary","slang"),
("NameToolkit","nametoolkit"),
("Th!ink","thinktutorial"),
("MIT OpenCourseWare","mitocw"),
("Lololyrics","lololyrics"),
("NRC","nrc"),
("Fotolog","fotolog"),
("ISBNdb.com","isbndb"),
("ebay.ph","ebayph"),
("Free Dictionary","freedict"),
("DistroWatch","distro"),
("Mashable","mashable"),
("Head-Fi","headfi"),
("LongURL.org","longurl"),
("Inspire","inspire"),
("SlickDeals","slickdeals"),
("Visualization Toolkit (VTK) class documentation (devel)","vtkcd"),
("About.com","about"),
("Shuttershock","shuttershock"),
("ArchLinux Packages","archpkg"),
("Barnes & Noble","barnesandnoble"),
("FDA","fda"),
("Clojure Docs","clojure"),
("LyricWiki","lyricswiki"),
("Google Reader","greader"),
("xkcd","xkcd"),
("Unicode Character Search","unicode"),
("Thesaurus.com","t"),
("ebay.ch","ebaych"),
("AlternativeTo","alternativeto"),
("MenuPages","mpph"),
("Miniclip","miniclip"),
("Tweet","tweet"),
("Robtex","robtex"),
("LyricWiki","lyricwiki"),
("Perseus Digital Library","perseus"),
("Wikipedia","wikipedia"),
("Google News","n"),
("ebay.ie","ebie"),
("MinePedia","minepedia"),
("Microsoft TechNet","technet"),
("LEO Dictionary Chinese","leoc"),
("FindJar.com","jar"),
("Beatport","beatport"),
("Java5 Docs","java5"),
("Google Images","image"),
("Micro Center","microcenter"),
("Google LT","glt"),
("Wink","wink"),
("John Lewis","jl"),
("ServerFault","serverfault"),
("Moby Games","mobygames"),
("Google Docs Viewer","gview"),
("MozBrowser.nl","mozbrowser"),
("OSNews","osnews"),
("Jetslide News Reader","jetslide"),
("CPAN -> GREP","gcpan"),
("Pyramid Web Application Development Framework","pyramid"),
("Newegg","newegg"),
("AJC.com","ajc"),
("JC Penney","jcpenney"),
("FreshMeat.net","freshmeat"),
("Python Docs","py"),
("Tweakers.net","tweakers"),
("Google Music","gmusic"),
("WorldCat.org","worldcat"),
("Library.nu","lnu"),
("DuckDuckGo","bang"),
("Sparkfun Electronics","sfe"),
("Etsy","etsy"),
("Every Click","everyclick"),
("Veoh","veoh"),
("Greplin","greplin"),
("Google Calendar","gcal"),
("How Stuff Works","howstuffworks"),
("Chrome Extensions","chrome"),
("Launchpad Bugs","lpbug"),
("Google PE","gpe"),
("Merriam-Webster","mw"),
("EncyclopediaDramatica.ch","ed"),
("Google SG","gsg"),
("START","start"),
("Scholarpedia","schloarpedia"),
("Zappos","zappos"),
("Google Video","gv"),
("Geocaching.com","geocaching"),
("Acronyms","acronyms"),
("Tokyo Toshokan","tt"),
("Iops","iops"),
("DailyMotion","dailymotion"),
("Mamma","mamma"),
("WOW Armory","wowarmory"),
("Rate Your Music","rateyourmusic"),
("Ada 2005 Manual","ada"),
("Clipstijl","clipstijl"),
("stock.xchng","sxc"),
("Google BE","gbe"),
("ArchLinux User Repository","archaur"),
("Amazon UK Kindle","kindleuk"),
("Slackbuilds","slackbuild"),
("Yahoo! Yellowpages","yellowpages"),
("Google Groups","ggroups"),
("WebWarper.com","webwarper"),
("The New Yorker","newyorker"),
("DomainTools.com","traceroute"),
("aniDB","anime"),
("Yeah Way!","yeahway"),
("Google Translate","gt"),
("Android Market","market"),
("GSMArena","gsmarena"),
("Google","g"),
("dribbble","dribbble"),
("Google Translate","translate"),
("Archlinux Forums","archlinux"),
("ArsTechnica","arstechnica"),
("Kobo","kobo"),
("National Geographic","nationalgeographic"),
("Apple Developer","cocoa"),
("All Posters","allposters"),
("Elektronik-Lexikon","elexikon"),
("Static Ice","staticice"),
("Open-Tran.eu","otran"),
("ISOHunt","isohunt"),
("WikiHow","wikihow"),
("Yandex","yaen"),
("SELFHTML","selfhtml"),
("Wetter.com","wetter"),
("HNsearch","searchyc"),
("Google TH","gth"),
("App Engine Docs","appengine"),
("Unicode Character Search","utf8"),
("Google EE","gee"),
("Racket","racket"),
("Wikipedia (SV)","wsv"),
("FileHippo","filehippo"),
("Pokepedia","pokepedia"),
("The Star Tribune","startribune"),
("Marktplaats","marktplaats"),
("Google HK","ghk"),
("Python3.2 Docs","python32"),
("Geizhals","giez"),
("GeoNames","geonames"),
("The Weather Network","twn"),
("Apache.org","apache"),
("Google Images","gimages"),
("Read the Docs","readthedocs"),
("Taringa!","taringa"),
("NFL.com","nfl"),
("Kickstarter","kickstarter"),
("IP Lookup","host"),
("CarMagazine.co.uk","car"),
("Google Photos","gp"),
("Google MX","gmx"),
("KeroDicas","kerodicas"),
("Appertium","apertium"),
("Overstock","overstock"),
("irc.netsplit.de","irc"),
("FilesTube","ftube"),
("Staples.com","staples"),
("Newark","newark"),
("Bloomberg","bloomberg"),
("CrunchBase","crunchbase"),
("BitBucket.org","bitbucket"),
("Wikipedia Nynorsk","wnn"),
("Geizhals","geiz"),
("LEO Dictionary English","leoe"),
("Zahe.me","zahe"),
("GameSpot","gamespot"),
("Locita","locita"),
("ebay.co.uk","ebuk"),
("Google AT","gat"),
("MySQL.com","mysql"),
("Lyricful","lyricful"),
("Electronic Frontier Foundation","eff"),
("Google Maps","googlemaps"),
("Touhouwiki (English)","thwiki"),
("Google IT","git"),
("The Pirate Bay","piratebay"),
("LMGTFY","lmgtfy"),
("CollegeBoard","collegeboard"),
("NBA.com","nba"),
("GitHub.com","github"),
("Booko","booko"),
("Bing Maps","bmaps"),
("Discogs","discogs"),
("Wiktionary","wikt"),
("Gephi","gephi"),
("DragonFly BSD manual pages","dfman"),
("Wikinews","wikinews"),
("Cdn js","cdn"),
("Tom's Hardware","tomshardware"),
("Django Docs","django"),
("Arduino","arduino"),
("The KoLWiki","kol"),
("Gawkr","gawker"),
("Google VE","gve"),
("WikiQuote","quotes"),
("Google RO","gro"),
("MetaFilter","metafilter"),
("Google Scholar","gscholar"),
("MongoDB","mongo"),
("Disney.com","disney"),
("Google PH","gph"),
("BoardGameGeek","boardgamegeek"),
("CPAN Dependencies Checker","cpandeps"),
("FolkTuneFinder","folktunefinder"),
("DistroWatch","distrowatch"),
("BitTorrentMonster","btmon"),
("Google JP","gjp"),
("NYPost","nypost"),
("GSA Advantage","gsa"),
("Macy's","macys"),
("Groklaw","groklaw"),
("SeatGeek","seatgeek"),
("Squidoo","squidoo"),
("Debian Hypertext Man Pages","dman"),
("Estante Virtual (by author and/or title)","evirtat"),
("matplotlib","mpl"),
("SparkNotes","sparknotes"),
("Uncyclopedia","unwiki"),
("Jinni","jinni"),
("Hayoo","hayoo"),
("EveryMac.com","everymac"),
("Play.com","play"),
("The Washington Post","washingtonpost"),
("SI.com","si"),
("HackADay","hackaday"),
("ESPN","espn"),
("SAS","sas"),
("Thumb Play","thumbplay"),
("MenuPages","menupages"),
("Bing News","bnews"),
("Wordreference en->fr","wref"),
("Veroot","veroot"),
("Autocar.co.uk","autocar"),
("Thumb Play","tones"),
("OneLook","onelook"),
("Scroogle","s"),
("viagogo","vgg"),
("Google IL","gik"),
("Google Translate","tr"),
("Gule Sider","gulesider"),
("The Globe And Mail","globeandmail"),
("Date Sort","date"),
("Meta Stack Overflow","metaso"),
("Dilbert","dilbert"),
("Mendeley","mendeley"),
("ebay.com.my","ebmy"),
("Jalopnik","jalopnik"),
("Mamont","mamont"),
("Pollstar","pollstar"),
("Java Docs","java"),
("Memory Alpha","startrek"),
("DealTaker","coupons"),
("Webtender","webtender"),
("Wikipedia (PT)","wpt"),
("Java4 Docs","java4"),
("YubNub","yubnub"),
("The Economist","economist"),
("Urban Dictionary","ud"),
("FilesTube","filestube"),
("Google (Past Year)","gyear"),
("CaptainCrawl","captaincrawl"),
("MTV","mtv"),
("Mozilla Developer Network","mdn"),
("Newsvine","newsvine"),
("MarkMail","markmail"),
("Upcoming","upcoming"),
("Appshopper","appshopper"),
("ArchLinux Wiki","archwiki"),
("Marmiton","marmiton"),
("CikeULike","citeul"),
("viagogo.de","vggde"),
("Redhat Bugzilla","rbugs"),
("Craigslist","craigslist"),
("Patternry","patternry"),
("Amazon.fr","amfr"),
("Google Blogs","gblogs"),
("Wikipedia (FR)","wfr"),
("SoundCloud","soundcloud"),
("Rails Docs","rails"),
("Wikibooks","wikibooks"),
("WikiCFP","cfp"),
("Google DE","gde"),
("Forrst","forrst"),
("The Full Wiki","thefullwiki"),
("Guild Wiki","guildwiki"),
("Debian Packages","dpkg"),
("The Nation","thenation"),
("Urban Dictionary","urban"),
("Gentoo Packages","ebuild"),
("Processing.org","processing"),
("Wieowie","wieowie"),
("Android Docs","android"),
("Google Docs","gdocs"),
("HNsearch","newsyc"),
("Arturogoga","arturogoga"),
("Google","glink"),
("Diaspora","diaspora"),
("Parashift.com","parashift"),
("Identi.ca","identica"),
("IEEE Xplore Digital Library","ieee"),
("Homebrew","brew"),
("Integer Sequences","oeis"),
("Go Programming Language","golang"),
("Jisho","jisho"),
("Find A Grave","grave"),
("Ecosia","ecosia"),
("Zillow.com","zillow"),
("BlackBook","blackbook"),
("Gentoo Wiki","gentoowiki"),
("Basketball Reference","bkr"),
("Real Academia Espanola","rae"),
("RPGGeek","rpggeek"),
("Apple Developer","appledev"),
("StackOverflow","stackoverflow"),
("foursquare","foursquare"),
("KickNews","kicknews"),
("Bulbapedia","bulbapedia"),
("Priberam","priberam"),
("MacUpdate","macupdate"),
("UltimateGuitar.com","chords"),
("Majors Books","majorsbooks"),
("Slate","slate"),
("Chilango","chilango"),
("Dictionary.com","dictionary"),
("Wikimedia Commons","wikic"),
("Acronyms","acro"),
("MyAnimeList","myanimelist"),
("WebMD","webmd"),
("IconFinder","icon"),
("Pinboard","pb"),
("WineHQ","winehq"),
("ebay.com.au","ebayau"),
("Linux.die.net man pages","die"),
("SimilarSites","similar"),
("Wikipedia (PL)","wpl"),
("HNsearch","hackernews"),
("matplotlib","matplotlib"),
("ebay.it","ebit"),
("Estante Virtual (description)","evirtdes"),
("Wikipedia (IT)","wit"),
("The Weather Channel","weather"),
("JSTOR","jstor"),
("Python3.1 Docs","python31"),
("SuperDownloads","superd"),
("Amazon.de","amde"),
("Libreria Universitaria","liberia"),
("Dictionary.com","pronounce"),
("ebay.com.hk","ebhk"),
("Gizmodo","gizmodo"),
("Belfry Web Comics","bwc"),
("Yahoo Finance","yf"),
("Google FR","gfr"),
("LWJGL","lwjgl"),
("MVNRepository","mvnrepository"),
("W3Schools.com","w3schools"),
("EmacsWiki","emacs"),
("Pagine Gialle","pagine"),
("Thesaurus.com","synonym"),
("Pandora","pandora"),
("JavaScript Docs","js"),
("Channel 4","channel4"),
("FILExt","filext"),
("Canada Post","capost"),
("Personal Package Archives for Ubuntu","ppa"),
("All Posters","posters"),
("Google AU","gau"),
("Google Accessible","gaccess"),
("SearchForPHP","sphp"),
("Minecraft Forums","mineforum"),
("TheMovieDB.org","tmdb"),
("Mamont","ftp"),
("ebay.fr","ebayfr"),
("Team Fortress Official Wiki","tf2wiki"),
("Python 3 docs","py3k"),
("EtymOnline.com","etymology"),
("USPS","usps"),
("DaFont","dafont"),
("Jobs.com","jobs"),
("Blekko","blekko"),
("WalMart","walmart"),
("Telegraph","telegraph"),
("NCBI dbSNP","dbsnp"),
("Diccionario de la lengua espanola","drae"),
("Hoepli","hoepli"),
("Wayback Machine","archive"),
("Fool.com","fool"),
("StackOverflow","so"),
("HUGO Gene Nomenclature Committee (HGNC)","hgnc"),
("Price Grabber","pricegrabber"),
("Google UA","gua"),
("FoxNews","foxnews"),
("ebay.at","ebayat"),
("Firefox Add-ons","firefox"),
("The Pirate Bay","tpb"),
("Google Maps","m"),
("Vimeo","vimeo"),
("SHODAN","shodanhq"),
("Il Sole 24 Ore","ilsole24ore"),
("MusicBrainz","mb"),
("Boost.org","boost"),
("KDE TechBase","ktechbase"),
("GModCentral","define"),
("Amazon.co.uk","amuk"),
("Google KR","gkr"),
("BestBuy","bestbuy"),
("RPMfind.net","rpm"),
("HowJSay","howjsay"),
("Zip.ca","zipca"),
("Google (Past Month)","gmonth"),
("Stack Exchange","stex"),
("WC3 Validator","validate"),
("SlideShare","slideshare"),
("NetHack Wiki","nethack"),
("The Full Wiki","fullwiki"),
("isup.me","isitdown"),
("Mimvi","mimvi"),
("Google Images","i"),
("LaserShip","laser"),
("Google Images","texture"),
("SpanishDict verb conjugation","sconj"),
("ArchLinux Packages","apackages"),
("Yandex","ya"),
("BugMeNot","bugmenot"),
("viagogo.co.uk","vgguk"),
("FreeBSD Ports","fports"),
("YouTube","youtube"),
("Firefox Addons","amo"),
("Google Bookmarks","gbk"),
("Songsterr","stabs"),
("BibleGateway","biblegateway"),
("Reuters","reuters"),
("Business Week","businessweek"),
("OnTrac","ontrac"),
("Entrez","entrez"),
("IconFinder","iconfinder"),
("Download.com","shareware"),
("BeerAdvocate","beer"),
("Nintendo Life","nintendolife"),
("FedEx","fedex"),
("mooTools Docs","mootools"),
("Beolingus De-en","beo"),
("Tumblr","tumblr"),
("Google Traffic","traffic"),
("Gentoo's Bugzilla","gbugs"),
("Wikipedia (UK)","wuk"),
("LinkedIn","li"),
("The Church of Jesus Christ of Latter-day Saints","lds"),
("Apple Developer","devapple"),
("Subsearch","subsearch"),
("WordNet","wordnet"),
("Google Images","googleimages"),
("D Reference","dp"),
("Thomas.loc.gov","thomas"),
("Friendster","friendster"),
("LinkUp","linkup"),
("OpenStreetMap","openstreet"),
("Yahoo! Answers","yanswers"),
("Flex Docs","flex"),
("Memory Alpha","memoryalpha"),
("Komputeko","komputeko"),
("ebay.be","ebaybe"),
("NewsMax.com","newsmax"),
("DistroWatch","iso"),
("SuperUser","su"),
("CBSNews","cbsnews"),
("Linux Packages Search","pkgs"),
("SMH.com.au","smh"),
("The Chicago Tribune","chicagotribune"),
("BitSnoop","bitsnoop"),
("TheMovieDB.org","themoviedb"),
("HowtoForge","htf"),
("Google Finance","gfinance"),
("Google Images","gim"),
("Peer Search","peer"),
("Google CN","gcn"),
("Feedbooks","feedbooks"),
("ThinkGeek","thinkgeek"),
("Fark.com","fark"),
("Kurrently","kurrently"),
("AS Lookup","asn"),
("SEC.gov","sec"),
("The Pirate Bay","thepiratebay"),
("StumbleUpon","stumbleupon"),
("Microsoft Clipart","clipart"),
("LibriVox","librivox"),
("MDBG Chinese-English dictionary","mdbg"),
("CBS Sports","cbssports"),
("CNET","cnet"),
("AllMusic","allmusic"),
("Make Magazine Blog","make"),
("Geizhals","geizhals"),
("Songsterr","songsterr"),
("Google CA","gca"),
("webcams.travel","webcams"),
("Abandonia","abandonia"),
("Ruby-lang.org","ruby"),
("Techcrunch","techcrunch"),
("Wikipedia","encyclopedia"),
("File info","fileinfo"),
("GeoIP Tool","geoip"),
("YouTube","watch"),
("Whitewater Search Engine","ww"),
("Truveo","truveo"),
("FuzzFind","fuzz"),
("the h","theh"),
("TheTVDB.com","tvdb"),
("Deezer","deezer"),
("www.heise.de","heise"),
("Beolingus De-pt","beopt"),
("RubyGems","gems"),
("Ask.com","ask"),
("Bartelby","bartlets"),
("DeviantART","da"),
("RedFlagDeals.com","redflagdeals"),
("Nokia QT Docs","qtc"),
("Lispdoc","lisp"),
("abcnotation.com","abcnotation"),
("43Things","43things"),
("Getty Images","gettyimages"),
("Ubuntu Forums","ubuntuf"),
("Encyclopedia Dramatica","dram"),
("Yahoo! Japan","yjp"),
("Amazon.com","a"),
("SuperUser","superuser"),
("YouTube","v"),
("NarutoPedia","naruto"),
("Slashdot","slashdot"),
("DilanDau","dilandau"),
("GameRankings.com","gamerankings"),
("Perldoc.perl.org","perldoc"),
("Imeem","imeem"),
("Pinvoke.net","pinvoke"),
("IRS","irs"),
("Ixquick","ixquick"),
("ESVonline","esvonline"),
("Mouser Electronics","mouser"),
("Google Maps","gmap"),
("Python2.7 Docs","python27"),
("Xanga","xanga"),
("Google Local","local"),
("TED","ted"),
("Google Translate","gtranslate"),
("Epinions","epinions"),
("One Across","anagram"),
("OpenSubtitles.org","osub"),
("Mednar","mednar"),
("Google New Zealand","gnz"),
("Shoutitout","shoutitout"),
("MusicBrainz","musicbrainz"),
("RadioTimes","radiotimes"),
("NewFFR","newffr"),
("Flightgear Forums","fgf"),
("Lyric Wiki","lyrics"),
("Rock, Paper, Shotgun","rps"),
("Google CO","gco"),
("Urban Dictionary","urbandictionary"),
("Eurogamer.net","eurogamer"),
("Arch Linux","aur"),
("Google","grelated"),
("Amazon.cn","amcn"),
("OpenBSD","openbsd"),
("iusethis.com","iusethis"),
("Compete","compete"),
("BBC.co.uk","bbc"),
("NzbMatrix","nzb"),
("TIGSource","tigsource"),
("ebay.com.au","ebau"),
("Synonymes","synonymes"),
("HNsearch","hn"),
("MenuPages","mpbo"),
("Blogspot","blogspot"),
("OpenStreetMap","openstreetmap"),
("ChaCha","chacha"),
("Multicolr Search Lab","multicolr"),
("O'Reilly","oreilly"),
("ebay.in","ebayin"),
("Emuparadise","emuparadise"),
("CheatCC","cheatcodes"),
("Debian pages in french language","debianfr"),
("Google SE","gse"),
("Wikimedia Commons","commons"),
("YabSearch","yabsearch"),
("Floodgap Gopher","gopher"),
("Libreria Universitaria","libuniversitaria"),
("iPlayer","iplayer"),
("MenuPages","mpny"),
("GriCal","gridcalendar"),
("Channel 5","channel5"),
("Fnac","fnac"),
("Debian Bugs","debbug"),
("Demonoid","demonoid"),
("BugMeNot","login"),
("Google UK","googleuk"),
("timeanddate","tz"),
("dmoz","dmoz"),
("Google CZ","gcz"),
("Seeks","seeks"),
("GNOME Bugzilla","gnomebugs"),
("Verb-o-Matic","verb"),
("SourceForge.net","sourceforge"),
("NetBSD manual pages","nbsdman"),
("Popsike","popsike"),
("Drupal API","drupalapi"),
("AllMovie","allmovie"),
("Google News","gn"),
("Expedia","expedia"),
("Eventful","eventful"),
("RPMfind.net","rpmfind"),
("Unity Answers","unity"),
("SearchForPHP","searchforphp"),
("Rdio","rdio"),
("Google AR","gar"),
("Google Maps","gm"),
("WordPress.org Themes","wpthemes"),
("LEO Dictionary French","leof"),
("ebay.in","ebin"),
("InstantWatcher","iw"),
("Trulia","trulia"),
("DefineForMe","d"),
("Wayback Machine","archived"),
("p3rl.org","perl"),
("reddit","reddit"),
("eMule Content Database","emule"),
("StageVu","stagevu"),
("Thingiverse","thingiverse"),
("Google with SSL","gssl"),
("boingboing","boingboing"),
("Google IN","gin"),
("Digi-Key","digikey"),
("Nyaa Torrents","nyaa"),
("Wired","wired"),
("AS3 Docs","as3"),
("MetaCPAN","cpan"),
("MenuPages","mpdc"),
("Userscripts","userscripts"),
("Pollstar","concerts"),
("Vogue.co.uk","vogueuk"),
("ebay.de","ebde"),
("Beolingus De-es","beoes"),
("Free Software Foundation Europe","fsfe"),
("Open Clip Art Library","oca"),
("LEO Dictionary","leo"),
("Site du Zer0","sdz"),
("p3rl.org","perlmod"),
("Topsy","topsy"),
("Wikipedia","wiki"),
("US Patent Database Search","patft"),
("Cplusplus.com","cpp"),
("Integer Sequences","sloanes"),
("Google Maps","maps"),
("Oxford English Dictionary","oed"),
("Nolo.com","nolo"),
("Lisp Docs","l1sp"),
("FindJar.com","findjar"),
("Google Images","img"),
("PackageMapping","track"),
("PerfSpot","perfspot"),
("Amazon.ca","amca"),
("RPM.pbone.net","pbone"),
("UltimateGuitar.com","gtabs"),
("ebay.ch","ebch"),
("Road & Track","randt"),
("Google Docs","gd"),
("ImageNet","imagenet"),
("UPS","ups"),
("is.gd","isgd"),
("StumbleUpon","stumble"),
("LOC.gov","loc"),
("Google News","gnews"),
("Tineye","tineye"),
("LATimes","latimes"),
("Yelp","yelp"),
("The DuckDuckGo Community","duckco"),
("IMSLP","imslp"),
("Albumart (DVD)","albumartdvd"),
("WordPress.org","wordpress"),
("Wikipedia (RU)","wru"),
("LinkedIn","linkedin"),
("Allegro","allegro"),
("Qt Reference Documentation","qt"),
("WebWarper.com","proxy"),
("World of Spectrum","wos"),
("OneRiot","oneriot"),
("Wolfram MathWorld","mathworld"),
("ISOHunt","torrent"),
("Flattr","flattr"),
("eBay","ebay"),
("CNN","cnn"),
("GoodReads","goodreads"),
("WowHead","wowhead"),
("Metro Lyrics","metrolyrics"),
("Java6 Docs","java6"),
("Circuit City","circuitcity"),
("Allocine.com","allocine"),
("Baseball-Reference","baseballreference"),
("Yandex Market","yandexm"),
("PostgreSQL.org","postgresql"),
("Ultimate Guitar","ultimateguitar"),
("The Chakra Project Wiki","chakrawiki"),
("AllDataSheet","datasheet"),
("Newsweek","newsweek"),
("JDK Docs","jdk"),
("iTV Player","itv"),
("Subscene","subscene"),
("New York Times","nyt"),
("Geegain Search","geegain"),
("Grooveshark","grooveshark"),
("True Knowledge","tk"),
("Evri","evri"),
("ServerFault","sf"),
("Diccionari de la llengua Catalana","diccionari"),
("ParkWhiz","parking"),
("Google NL","gnl"),
("Codeigniter User Guide","ci"),
("Google Finance","gf"),
("Financial Times","ft"),
("XDA-Developers Forum","xdaf"),
("TuneIn","tunein"),
("MSNBC","msnbc"),
("Dream In Code","dreamincode"),
("Institut d'Estudis Catalans","iec"),
("CareerBuilder","careerbuilder"),
("Open Site Explorer","ose"),
("Open Site Explorer","linkscape"),
("Amazon.it","amit"),
("BattleNet","wowbattlenet"),
("lovefilm.com","lovefilm"),
("UltimateGuitar.com","btabs"),
("Google BG","gbg"),
("The Guardian","guardian"),
("Hoogle","hoogle"),
("Google SK","gsk"),
("Btjunkie","btjunkie"),
("SmallSafari","smallsafari"),
("CTAN.org","ctan"),
("Steam","steam"),
("FlickPeek","flickpeek"),
("Danbooru","danbooru"),
("Kazazz","kazazz"),
("Chefkoch","chefkoch"),
("Dream In Code","dic"),
("MySpace","myspace"),
("Matlab File Exchange","matlabfx"),
("Geocaching.com","geocache"),
("Amazon.com","amazon"),
("Google Books","gbooks"),
("Charity Navigator","charity"),
("MIT OpenCourseWare","ocw"),
("Gutenberg text content","bookmine"),
("BlackBook","blackbookmag"),
("Khronos","khronos"),
("Earth911.com","earth911"),
("Punchfork","punchfork"),
("CPAN -> GREP","grepcpan"),
("Google CL","gcl"),
("Ruby-doc.org","rubydoc"),
("SFGate","sfgate"),
("Goosh","goosh"),
("Good old games","gog"),
("Instructables","instructables"),
("Mozilla Developer Center","mdc"),
("SkyRock","skyrock"),
("pastebin","pastebin"),
("LaserShip","lasership"),
("PubMed","pubmed"),
("http://framework.zend.com","zf"),
("NPR.org","npr"),
("Historious","historious"),
("Orkut","orkut"),
("Google Cache","cache"),
("Free Dictionary","freedictionary"),
("Wookiepedia","starwars"),
("Cambridge Advanced Learner's Dictionary","cald"),
("Bing Images","bingimages"),
("Book Finder","bookfinder"),
("Terraria Wiki","terraria"),
("Google (Past Week)","gweek"),
("OpenSubtitles.org","opensubtitles"),
("Quora","quora"),
("Mathematics - Stack Exchange","mathse"),
("iStockPhoto","stockphotos"),
("GoDaddy","domain"),
("Google Images","pictures"),
("Google Maps","googlemap"),
("Gentoo Packages","gpackages"),
("Rotten Tomatoes","rt"),
("Verb-o-Matic","verbomatic"),
("Hulu","hulu"),
("Homestar Runner Wiki","hrwiki"),
("Encyclopedia Metallum (The Metal Archives)","metal"),
("Soso","soso"),
("Britannica.com","britannica"),
("DealExtreme","dx"),
("RosettaCode.org","rosettacode"),
("Allmusic Album Search","album"),
("RedTram","redtram"),
("Oopon","oopon"),
("Dealextreme","dealextreme"),
("CafePress","cafepress"),
("da.wikipedia.org","wda"),
("WhatIs.com","whatis"),
("Drupal","drupal"),
("C-SPAN","cspan"),
("SimplyHired","sh"),
("BoardGameGeek","bgg"),
("startpage.com","startpage"),
("Car and Driver","caranddriver"),
("Debian Bugs","dbugs"),
("Swagbucks","swagbucks"),
("jQuery Docs","jquery"),
("Punchfork","recipes"),
("Shopzilla","shopzilla"),
("Vogue.com","vogue"),
("Bing Videos","bv"),
("Metacritic","metacritic"),
("EmacsWiki","emacswiki"),
("Epicurious","epicurious"),
("Google Shopping","gs"),
("Library.nu","gigapedia"),
("QRZ.com","qrz"),
("Yahoo Finance","yfinance"),
("FileHippo","file"),
("DownForEveryone?","updown"),
("Ikea","ikea"),
("Amazon MP3 Store","amazonmp3"),
("Quantcast","quantcast"),
("Google","google"),
("Google LV","glv"),
("World of Spectrum","worldofspectrum"),
("BlogTalkRadio","blogtalkradio"),
("Google Cache","gcache"),
("Reciva","reciva"),
("PBS","pbs"),
("TradeMe","trademe"),
("CellarTracker","cellartracker"),
("LinuxFr.org","linuxfr"),
("Library Genesis","genesis"),
("Adobe","adobe"),
("MetaCPAN","mcpan"),
("Flipkart","flipkart"),
("Huffington Post","huffingtonpost"),
("la Repubblica","repubblica"),
("dig Lookup","dig"),
("EDGAR","edgar"),
("ohloh","ohloh"),
("UK Parliament","ukp"),
("Python Docs","python"),
)

from urllib import FancyURLopener

class MyOpener(FancyURLopener):
    version = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.8.1.11) Gecko/20071127 Firefox/2.0.0.11'

opener = MyOpener()

import random,urllib,time
START="<meta http-equiv='refresh' content='0; url="

for name,bang in bangs:
    print name
    rnd = "%x" % random.randint(100000, 16777215)
    s = opener.open("http://duckduckgo.com/?q=%s%s" % (rnd,urllib.quote("!"+bang))).read()
    print s
    s = s.replace(rnd,"PLACEHOLDER")
    urls = s.find(START)

    if urls < 0:
        raise "FFUU"

    urls += len(START)
    url = s[urls:s.find("'",urls)]

    print '"%s":"%s",' % (bang,urllib.quote(url))
    time.sleep(1)



