#!/bin/bash

find -L /var/lib/transmission-daemon/downloads/ -size +20M -and \( -iname "*.avi" -or -iname "*.mkv" -or -iname "*.mp4" -or -iname "*.3gp" \) | while read show
do
    sub=${show%.*}.srt

    if [ ! -e "$sub" ] || [ `stat -c%s "$sub"` -lt 10 ]
    then
        print "-- Downloading subs for $show"
        download_subs "$show"
    fi
done

